{
 "title": "Minecraft server",
 "description": "v2.2 - add thread states terminated, timed waiting, align colors",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(jmx_exporter_build_info,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\",job=~\"$job\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\",job=\"$job\",app=~\"$app\"},instance)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(jmx_exporter_build_info{namespace=~\"$namespace\",job=\"$job\",app=~\"$app\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job = \"minecraft-game\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_AvailableProcessors{job=\"minecraft\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{job=\"minecraft\", area=\"heap\"}",
     "legendFormat": "{{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"minecraft\", area=\"heap\"}"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Map Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minecraft_world_size_bytes", "legendFormat": "__auto" }
   ]
  },
  { "title": "Server Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Server ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "mc_tick_duration_average{job='minecraft-game'}",
     "legendFormat": "{{}}"
    }
   ]
  },
  {
   "title": "Server TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "mc_tps{job='minecraft-game'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Player Online History",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(mc_player_online{name!='naty'}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Entities Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(mc_entities_total) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"minecraft\"}",
     "legendFormat": "JVM Process - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_processor_systemcpuload{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "Overall System - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  {
   "title": "Chunks Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(mc_loaded_chunks_total) by (world)",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"minecraft\", area=\"heap\"}",
     "legendFormat": "Heap Memory"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"heap\",job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{area}}-committed - {{app}} {{pod}} {{instance}}"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}",
     "legendFormat": "{{area}}-used - {{app}} {{pod}} {{instance}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Garbage Collection Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=~\"$instance\", job=\"$job\", app=~\"$app\", pod=~\"$pod\"}[1m]) \n/ \nincrease(jvm_gc_collection_seconds_count{instance=~\"$instance\", job=\"$job\", app=~\"$app\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Throughput",
   "type": "stat",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "GC Throughput Evolution",
   "type": "timeseries",
   "description": "These calculations are experimental and need yet to be compared and validated against known correct results.  The way it is built does not work for multiple simultaneous JVMs, so accuracy requires selecting only one.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(\n    (\n        sum(max(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))-\n        sum(min(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}))\n    )\n    /\n    (${__to:date:seconds}-${__from:date:seconds})\n)",
     "legendFormat": "Throughput"
    }
   ]
  },
  {
   "title": "GC Time (period)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_collection_seconds_sum{job=\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__range]))",
     "legendFormat": "{{job}}-{{gc}} {{pod}}"
    }
   ]
  }
 ]
}